# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
  - "3.6"
  - "pypy3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script: coverage run --source=drf_compound_fields setup.py test
after_success: coveralls
